/**
 * Export Utilities for 3D CAD Drawing App
 * Provides downloads for OBJ, DXF, JSON, and Viewport PNG snapshots.
 */

// Helper to trigger browser file download
export function downloadFile(filename, content, mimeType = 'text/plain') {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

/**
 * Export drawing as Wavefront .OBJ format
 */
export function exportToOBJ(lines, filename = 'cad_drawing.obj') {
    if (!lines || lines.length === 0) {
        alert('No lines to export!');
        return;
    }

    let objText = `# 3D CAD Drawing Export\n# Generated by 3D CAD Gesture App\n\n`;
    
    // Write vertices and build line indices
    let vertexIndex = 1;
    lines.forEach((line, idx) => {
        const [sx, sy, sz] = line.start;
        const [ex, ey, ez] = line.end;
        
        objText += `v ${sx.toFixed(6)} ${sy.toFixed(6)} ${sz.toFixed(6)}\n`;
        objText += `v ${ex.toFixed(6)} ${ey.toFixed(6)} ${ez.toFixed(6)}\n`;
        objText += `l ${vertexIndex} ${vertexIndex + 1}\n\n`;
        
        vertexIndex += 2;
    });

    downloadFile(filename, objText, 'text/plain');
}

/**
 * Export drawing as AutoCAD .DXF format
 */
export function exportToDXF(lines, filename = 'cad_drawing.dxf') {
    if (!lines || lines.length === 0) {
        alert('No lines to export!');
        return;
    }

    let dxfText = `0\nSECTION\n2\nHEADER\n0\nENDSEC\n`;
    dxfText += `0\nSECTION\n2\nTABLES\n0\nENDSEC\n`;
    dxfText += `0\nSECTION\n2\nBLOCKS\n0\nENDSEC\n`;
    dxfText += `0\nSECTION\n2\nENTITIES\n`;

    lines.forEach((line) => {
        const [sx, sy, sz] = line.start;
        const [ex, ey, ez] = line.end;

        dxfText += `0\nLINE\n8\n0\n`;
        // Start point
        dxfText += `10\n${sx.toFixed(6)}\n20\n${sy.toFixed(6)}\n30\n${sz.toFixed(6)}\n`;
        // End point
        dxfText += `11\n${ex.toFixed(6)}\n21\n${ey.toFixed(6)}\n31\n${ez.toFixed(6)}\n`;
    });

    dxfText += `0\nENDSEC\n0\nEOF\n`;

    downloadFile(filename, dxfText, 'application/dxf');
}

/**
 * Export full project state as .JSON format
 */
export function exportToJSON(lines, planeRotation, filename = 'cad_project.json') {
    if (!lines || lines.length === 0) {
        alert('No lines to export!');
        return;
    }

    const projectData = {
        version: '1.0',
        exportedAt: new Date().toISOString(),
        planeRotation: planeRotation || [0, 0, 0],
        lineCount: lines.length,
        lines: lines
    };

    const jsonString = JSON.stringify(projectData, null, 2);
    downloadFile(filename, jsonString, 'application/json');
}

/**
 * Capture high-resolution viewport PNG snapshot
 */
export function exportSnapshotPNG(filename = 'cad_snapshot.png') {
    const canvas = document.querySelector('canvas');
    if (!canvas) {
        alert('Canvas viewport not found!');
        return;
    }

    try {
        const dataUrl = canvas.toDataURL('image/png');
        const link = document.createElement('a');
        link.href = dataUrl;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    } catch (err) {
        console.error('Error capturing snapshot:', err);
        alert('Failed to capture snapshot. Ensure preserveDrawingBuffer is enabled on Canvas.');
    }
}
