/**
 * exportUtils.js - Exporter & Persistence Utilities for 3D CAD Drawing App
 * 
 * Supports:
 * - Wavefront .OBJ (Multi-point polylines, curves, rectangles, and line segments)
 * - AutoCAD .DXF (Standard CAD polyline & line entities)
 * - Project .JSON (Complete coordinate preservation & metadata)
 * - Viewport .PNG high-resolution snapshot
 */

// Helper to trigger browser file download
export function downloadFile(filename, content, mimeType = 'text/plain') {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

import * as THREE from 'three';
import { Profile2D, ExtrusionEngine, SolidMesh } from '../cad/geometry/index.js';

/**
 * Export CAD model as Wavefront .OBJ format.
 * If an object is a 3D Solid, exports complete 3D boundary representation
 * with vertices, normals, and 3D faces ('f') forming a closed, watertight volume.
 * If an object is a 2D sketch, exports polyline elements ('l').
 */
export function exportToOBJ(cadObjects, defaultPlaneRotation = [0, 0, 0], filename = 'cad_model.obj') {
    if (!cadObjects || cadObjects.length === 0) {
        alert('No CAD objects to export!');
        return;
    }

    let objText = `# 3D CAD Model Export (Solid B-Rep & Mesh)\n`;
    objText += `# Generated by Gesture-Controlled 3D CAD Modeling Kernel\n`;
    objText += `# Objects: ${cadObjects.length}\n\n`;

    let globalVertexIndex = 1;

    cadObjects.forEach((obj, objIdx) => {
        const height = Math.max(0, obj.extrudeHeight ?? ((obj.scaleZ && obj.scaleZ > 0.05 && obj.scaleZ !== 1) ? obj.scaleZ : 0));
        const pos = obj.planePosition || [0, 0, 0];
        const rot = obj.planeRotation || defaultPlaneRotation || [0, 0, 0];

        // -------------------------------------------------------------
        // CATEGORY 3: 3D SOLID MODEL EXPORT (Complete 3D Faces 'f')
        // -------------------------------------------------------------
        if (height > 0.01) {
            let solid = obj.solidMesh;
            if (!solid || typeof solid.toOBJ !== 'function') {
                const prof = obj.profile || new Profile2D({
                    points: obj.points || (obj.start && obj.end ? [obj.start, obj.end] : []),
                    type: obj.type || 'FREEHAND',
                    isClosed: obj.type === 'RECTANGLE'
                });
                solid = ExtrusionEngine.extrude(prof, height);
            }

            objText += `o CAD_Solid_${objIdx + 1}_${obj.type || 'SOLID'}\n`;
            const result = solid.toOBJ(globalVertexIndex, pos, rot);
            objText += result.objText;
            globalVertexIndex = result.nextIndex;
            return;
        }

        // -------------------------------------------------------------
        // CATEGORY 1: 2D SKETCH / PROFILE EXPORT (Polylines 'l')
        // -------------------------------------------------------------
        objText += `o CAD_Sketch_${objIdx + 1}_${obj.type || 'SKETCH'}\n`;
        let pts = [];
        if (obj.points && obj.points.length > 0) {
            pts = obj.points;
        } else if (obj.start && obj.end) {
            pts = [obj.start, obj.end];
        }
        if (pts.length < 2) return;

        const euler = new THREE.Euler(...rot);
        const quat = new THREE.Quaternion().setFromEuler(euler);
        const posVec = new THREE.Vector3(...pos);

        const startIdx = globalVertexIndex;
        pts.forEach((pt) => {
            const vWorld = new THREE.Vector3(pt[0], pt[1] || 0, pt[2]).applyQuaternion(quat).add(posVec);
            objText += `v ${vWorld.x.toFixed(6)} ${vWorld.y.toFixed(6)} ${vWorld.z.toFixed(6)}\n`;
            globalVertexIndex++;
        });

        if (obj.type === 'RECTANGLE' && pts.length >= 4) {
            objText += `l ${startIdx} ${startIdx + 1} ${startIdx + 2} ${startIdx + 3} ${startIdx}\n\n`;
        } else {
            const indices = [];
            for (let i = 0; i < pts.length; i++) {
                indices.push(startIdx + i);
            }
            objText += `l ${indices.join(' ')}\n\n`;
        }
    });

    downloadFile(filename, objText, 'text/plain');
}

/**
 * Export CAD solids as standard ASCII .STL file format
 */
export function exportToSTL(cadObjects, filename = 'cad_model.stl') {
    if (!cadObjects || cadObjects.length === 0) {
        alert('No CAD objects to export!');
        return;
    }

    let stl = `solid CAD_GESTURE_MODEL\n`;
    let solidCount = 0;

    cadObjects.forEach((obj, objIdx) => {
        const height = Math.max(0, obj.extrudeHeight ?? ((obj.scaleZ && obj.scaleZ > 0.05 && obj.scaleZ !== 1) ? obj.scaleZ : 0));
        if (height <= 0.01) return;

        let solid = obj.solidMesh;
        if (!solid || typeof solid.toThreeGeometry !== 'function') {
            const prof = obj.profile || new Profile2D({
                points: obj.points || (obj.start && obj.end ? [obj.start, obj.end] : []),
                type: obj.type || 'FREEHAND',
                isClosed: obj.type === 'RECTANGLE'
            });
            solid = ExtrusionEngine.extrude(prof, height);
        }

        const rot = obj.planeRotation || [0, 0, 0];
        const pos = obj.planePosition || [0, 0, 0];
        const euler = new THREE.Euler(...rot);
        const quat = new THREE.Quaternion().setFromEuler(euler);
        const posVec = new THREE.Vector3(...pos);

        for (const face of solid.faces) {
            if (face.length < 3) continue;
            for (let i = 1; i < face.length - 1; i++) {
                const p0 = new THREE.Vector3(...solid.vertices[face[0]]).applyQuaternion(quat).add(posVec);
                const p1 = new THREE.Vector3(...solid.vertices[face[i]]).applyQuaternion(quat).add(posVec);
                const p2 = new THREE.Vector3(...solid.vertices[face[i + 1]]).applyQuaternion(quat).add(posVec);

                const e1 = new THREE.Vector3().subVectors(p1, p0);
                const e2 = new THREE.Vector3().subVectors(p2, p0);
                const norm = new THREE.Vector3().crossVectors(e1, e2).normalize();

                stl += `  facet normal ${norm.x.toFixed(6)} ${norm.y.toFixed(6)} ${norm.z.toFixed(6)}\n`;
                stl += `    outer loop\n`;
                stl += `      vertex ${p0.x.toFixed(6)} ${p0.y.toFixed(6)} ${p0.z.toFixed(6)}\n`;
                stl += `      vertex ${p1.x.toFixed(6)} ${p1.y.toFixed(6)} ${p1.z.toFixed(6)}\n`;
                stl += `      vertex ${p2.x.toFixed(6)} ${p2.y.toFixed(6)} ${p2.z.toFixed(6)}\n`;
                stl += `    endloop\n`;
                stl += `  endfacet\n`;
            }
        }
        solidCount++;
    });

    stl += `endsolid CAD_GESTURE_MODEL\n`;

    if (solidCount === 0) {
        alert('No 3D solid objects to export to STL. Extrude a sketch first!');
        return;
    }

    downloadFile(filename, stl, 'text/plain');
}

/**
 * Export CAD drawing as AutoCAD .DXF format
 */
export function exportToDXF(cadObjects, filename = 'cad_drawing.dxf') {
    if (!cadObjects || cadObjects.length === 0) {
        alert('No CAD objects to export!');
        return;
    }

    let dxfText = `0\nSECTION\n2\nHEADER\n0\nENDSEC\n`;
    dxfText += `0\nSECTION\n2\nTABLES\n0\nENDSEC\n`;
    dxfText += `0\nSECTION\n2\nBLOCKS\n0\nENDSEC\n`;
    dxfText += `0\nSECTION\n2\nENTITIES\n`;

    cadObjects.forEach((obj) => {
        const height = Math.max(0, obj.extrudeHeight ?? ((obj.scaleZ && obj.scaleZ > 0.05 && obj.scaleZ !== 1) ? obj.scaleZ : 0));
        const rot = obj.planeRotation || [0, 0, 0];
        const pos = obj.planePosition || [0, 0, 0];
        const euler = new THREE.Euler(...rot);
        const quat = new THREE.Quaternion().setFromEuler(euler);
        const posVec = new THREE.Vector3(...pos);

        // 3D Solid Export: 3DFACE entities
        if (height > 0.01) {
            let solid = obj.solidMesh;
            if (!solid) {
                const prof = obj.profile || new Profile2D({
                    points: obj.points || (obj.start && obj.end ? [obj.start, obj.end] : []),
                    type: obj.type || 'FREEHAND',
                    isClosed: obj.type === 'RECTANGLE'
                });
                solid = ExtrusionEngine.extrude(prof, height);
            }

            for (const face of solid.faces) {
                if (face.length < 3) continue;
                for (let i = 1; i < face.length - 1; i++) {
                    const p0 = new THREE.Vector3(...solid.vertices[face[0]]).applyQuaternion(quat).add(posVec);
                    const p1 = new THREE.Vector3(...solid.vertices[face[i]]).applyQuaternion(quat).add(posVec);
                    const p2 = new THREE.Vector3(...solid.vertices[face[i + 1]]).applyQuaternion(quat).add(posVec);

                    dxfText += `0\n3DFACE\n8\n0\n`;
                    dxfText += `10\n${p0.x.toFixed(6)}\n20\n${p0.y.toFixed(6)}\n30\n${p0.z.toFixed(6)}\n`;
                    dxfText += `11\n${p1.x.toFixed(6)}\n21\n${p1.y.toFixed(6)}\n31\n${p1.z.toFixed(6)}\n`;
                    dxfText += `12\n${p2.x.toFixed(6)}\n22\n${p2.y.toFixed(6)}\n32\n${p2.z.toFixed(6)}\n`;
                    dxfText += `13\n${p2.x.toFixed(6)}\n23\n${p2.y.toFixed(6)}\n33\n${p2.z.toFixed(6)}\n`;
                }
            }
            return;
        }

        let pts = [];
        if (obj.points && obj.points.length > 0) {
            pts = obj.points;
        } else if (obj.start && obj.end) {
            pts = [obj.start, obj.end];
        }

        if (pts.length < 2) return;

        const count = pts.length;
        const isClosed = obj.type === 'RECTANGLE';

        // Write as consecutive 3D LINE entities for maximum CAD viewer compatibility
        for (let i = 0; i < count - 1; i++) {
            const p1 = pts[i];
            const p2 = pts[i + 1];

            dxfText += `0\nLINE\n8\n0\n`;
            dxfText += `10\n${p1[0].toFixed(6)}\n20\n${p1[1].toFixed(6)}\n30\n${p1[2].toFixed(6)}\n`;
            dxfText += `11\n${p2[0].toFixed(6)}\n21\n${p2[1].toFixed(6)}\n31\n${p2[2].toFixed(6)}\n`;
        }

        // Close rectangle loop
        if (isClosed && count >= 4) {
            const p1 = pts[count - 1];
            const p2 = pts[0];
            dxfText += `0\nLINE\n8\n0\n`;
            dxfText += `10\n${p1[0].toFixed(6)}\n20\n${p1[1].toFixed(6)}\n30\n${p1[2].toFixed(6)}\n`;
            dxfText += `11\n${p2[0].toFixed(6)}\n21\n${p2[1].toFixed(6)}\n31\n${p2[2].toFixed(6)}\n`;
        }
    });

    dxfText += `0\nENDSEC\n0\nEOF\n`;

    downloadFile(filename, dxfText, 'application/dxf');
}

/**
 * Export full project state as .JSON format
 * Preserves ALL raw coordinate arrays without reduction.
 */
export function exportToJSON(cadObjects, planeRotation = [0, 0, 0], filename = 'cad_project.json') {
    if (!cadObjects || cadObjects.length === 0) {
        alert('No CAD objects to export!');
        return;
    }

    let totalPoints = 0;
    cadObjects.forEach((obj) => {
        if (obj.points) totalPoints += obj.points.length;
        else if (obj.start && obj.end) totalPoints += 2;
    });

    const projectData = {
        version: '2.0',
        exportedAt: new Date().toISOString(),
        planeRotation: planeRotation || [0, 0, 0],
        objectCount: cadObjects.length,
        totalPointsStored: totalPoints,
        cadObjects: cadObjects,
        // Legacy lines format compatibility
        lines: cadObjects.map((obj) => {
            if (obj.start && obj.end) return { start: obj.start, end: obj.end };
            if (obj.points && obj.points.length >= 2) {
                return { start: obj.points[0], end: obj.points[obj.points.length - 1] };
            }
            return null;
        }).filter(Boolean)
    };

    const jsonString = JSON.stringify(projectData, null, 2);
    downloadFile(filename, jsonString, 'application/json');
}

/**
 * Capture high-resolution viewport PNG snapshot
 */
export function exportSnapshotPNG(filename = 'cad_snapshot.png') {
    const canvas = document.querySelector('canvas');
    if (!canvas) {
        alert('Canvas viewport not found!');
        return;
    }

    try {
        const dataUrl = canvas.toDataURL('image/png');
        const link = document.createElement('a');
        link.href = dataUrl;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    } catch (err) {
        console.error('Error capturing snapshot:', err);
        alert('Failed to capture snapshot. Ensure preserveDrawingBuffer is enabled on Canvas.');
    }
}
