/**
 * exportUtils.js - Exporter & Persistence Utilities for 3D CAD Drawing App
 * 
 * Supports:
 * - Wavefront .OBJ (Multi-point polylines, curves, rectangles, and line segments)
 * - AutoCAD .DXF (Standard CAD polyline & line entities)
 * - Project .JSON (Complete coordinate preservation & metadata)
 * - Viewport .PNG high-resolution snapshot
 */

// Helper to trigger browser file download
export function downloadFile(filename, content, mimeType = 'text/plain') {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
}

/**
 * Export CAD model as Wavefront .OBJ format
 * Preserves every coordinate in multi-point curves, lines, and rectangles.
 */
export function exportToOBJ(cadObjects, planeRotation = [0, 0, 0], filename = 'cad_model.obj') {
    if (!cadObjects || cadObjects.length === 0) {
        alert('No CAD objects to export!');
        return;
    }

    let objText = `# 3D CAD Model Export\n`;
    objText += `# Generated by Gesture-Controlled 3D CAD System\n`;
    objText += `# Objects: ${cadObjects.length}\n\n`;

    let globalVertexIndex = 1;

    cadObjects.forEach((obj, objIdx) => {
        objText += `o CAD_Object_${objIdx + 1}_${obj.type || 'POLYLINE'}\n`;

        let pts = [];
        if (obj.points && obj.points.length > 0) {
            pts = obj.points;
        } else if (obj.start && obj.end) {
            pts = [obj.start, obj.end];
        }

        if (pts.length < 2) return;

        // Write all vertices
        const startIdx = globalVertexIndex;
        pts.forEach((pt) => {
            objText += `v ${pt[0].toFixed(6)} ${pt[1].toFixed(6)} ${pt[2].toFixed(6)}\n`;
            globalVertexIndex++;
        });

        // Write line / polyline elements
        if (obj.type === 'RECTANGLE' && pts.length >= 4) {
            // Closed loop
            objText += `l ${startIdx} ${startIdx + 1} ${startIdx + 2} ${startIdx + 3} ${startIdx}\n\n`;
        } else {
            // Sequential polyline
            const indices = [];
            for (let i = 0; i < pts.length; i++) {
                indices.push(startIdx + i);
            }
            objText += `l ${indices.join(' ')}\n\n`;
        }
    });

    downloadFile(filename, objText, 'text/plain');
}

/**
 * Export CAD drawing as AutoCAD .DXF format
 */
export function exportToDXF(cadObjects, filename = 'cad_drawing.dxf') {
    if (!cadObjects || cadObjects.length === 0) {
        alert('No CAD objects to export!');
        return;
    }

    let dxfText = `0\nSECTION\n2\nHEADER\n0\nENDSEC\n`;
    dxfText += `0\nSECTION\n2\nTABLES\n0\nENDSEC\n`;
    dxfText += `0\nSECTION\n2\nBLOCKS\n0\nENDSEC\n`;
    dxfText += `0\nSECTION\n2\nENTITIES\n`;

    cadObjects.forEach((obj) => {
        let pts = [];
        if (obj.points && obj.points.length > 0) {
            pts = obj.points;
        } else if (obj.start && obj.end) {
            pts = [obj.start, obj.end];
        }

        if (pts.length < 2) return;

        const count = pts.length;
        const isClosed = obj.type === 'RECTANGLE';

        // Write as consecutive 3D LINE entities for maximum CAD viewer compatibility
        for (let i = 0; i < count - 1; i++) {
            const p1 = pts[i];
            const p2 = pts[i + 1];

            dxfText += `0\nLINE\n8\n0\n`;
            dxfText += `10\n${p1[0].toFixed(6)}\n20\n${p1[1].toFixed(6)}\n30\n${p1[2].toFixed(6)}\n`;
            dxfText += `11\n${p2[0].toFixed(6)}\n21\n${p2[1].toFixed(6)}\n31\n${p2[2].toFixed(6)}\n`;
        }

        // Close rectangle loop
        if (isClosed && count >= 4) {
            const p1 = pts[count - 1];
            const p2 = pts[0];
            dxfText += `0\nLINE\n8\n0\n`;
            dxfText += `10\n${p1[0].toFixed(6)}\n20\n${p1[1].toFixed(6)}\n30\n${p1[2].toFixed(6)}\n`;
            dxfText += `11\n${p2[0].toFixed(6)}\n21\n${p2[1].toFixed(6)}\n31\n${p2[2].toFixed(6)}\n`;
        }
    });

    dxfText += `0\nENDSEC\n0\nEOF\n`;

    downloadFile(filename, dxfText, 'application/dxf');
}

/**
 * Export full project state as .JSON format
 * Preserves ALL raw coordinate arrays without reduction.
 */
export function exportToJSON(cadObjects, planeRotation = [0, 0, 0], filename = 'cad_project.json') {
    if (!cadObjects || cadObjects.length === 0) {
        alert('No CAD objects to export!');
        return;
    }

    let totalPoints = 0;
    cadObjects.forEach((obj) => {
        if (obj.points) totalPoints += obj.points.length;
        else if (obj.start && obj.end) totalPoints += 2;
    });

    const projectData = {
        version: '2.0',
        exportedAt: new Date().toISOString(),
        planeRotation: planeRotation || [0, 0, 0],
        objectCount: cadObjects.length,
        totalPointsStored: totalPoints,
        cadObjects: cadObjects,
        // Legacy lines format compatibility
        lines: cadObjects.map((obj) => {
            if (obj.start && obj.end) return { start: obj.start, end: obj.end };
            if (obj.points && obj.points.length >= 2) {
                return { start: obj.points[0], end: obj.points[obj.points.length - 1] };
            }
            return null;
        }).filter(Boolean)
    };

    const jsonString = JSON.stringify(projectData, null, 2);
    downloadFile(filename, jsonString, 'application/json');
}

/**
 * Capture high-resolution viewport PNG snapshot
 */
export function exportSnapshotPNG(filename = 'cad_snapshot.png') {
    const canvas = document.querySelector('canvas');
    if (!canvas) {
        alert('Canvas viewport not found!');
        return;
    }

    try {
        const dataUrl = canvas.toDataURL('image/png');
        const link = document.createElement('a');
        link.href = dataUrl;
        link.download = filename;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
    } catch (err) {
        console.error('Error capturing snapshot:', err);
        alert('Failed to capture snapshot. Ensure preserveDrawingBuffer is enabled on Canvas.');
    }
}
